### ISSUE TITLE
We can’t connect to the server at www.filicious.org.

### ISSUE THREAD

**Issue by stamster** [filicious/core#86]
We can’t connect to the server at www.filicious.org.

Is there documentation avail somewhere else?

Project still active?

**Comment by tristanlins** [comment]
The domain does not exists anymore, please visit https://filicious.github.io/

But the project is inactive since 2015

**Comment by stamster** [comment]
Good thanks, that link shall be updated in the README file :+1:

**Comment by stamster** [comment]
https://github.com/filicious/core/pull/87
